package br.com.codex.v1.utilitario;

import br.com.codex.v1.domain.repository.EventosFolhaRepository;
import br.com.codex.v1.domain.rh.EventosFolha;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
public class ImportaEventosFolha {

    @Autowired
    private EventosFolhaRepository eventosFolhaRepository;

    public void importaEventosFolha(){

        List<EventosFolha> listaEventosFolha = new ArrayList<>();

        listaEventosFolha.add(new EventosFolha(null, "1", "Normais diurnas"));
        listaEventosFolha.add(new EventosFolha(null, "2", "Adiantamento salário"));
        listaEventosFolha.add(new EventosFolha(null, "5", "Horas repouso remunerado Diruno"));
        listaEventosFolha.add(new EventosFolha(null, "6", "Desconto dias de faltas"));
        listaEventosFolha.add(new EventosFolha(null, "7", "Desconto dias de Descanso Semanal Remunerado (DSR)"));
        listaEventosFolha.add(new EventosFolha(null, "8", "Horas de Atestado Médico"));
        listaEventosFolha.add(new EventosFolha(null, "9", "dias de atestado médico"));
        listaEventosFolha.add(new EventosFolha(null, "12", "Horas Normais Noturnas"));
        listaEventosFolha.add(new EventosFolha(null, "13", "Redução Horário noturno"));
        listaEventosFolha.add(new EventosFolha(null, "14", "Adicional noturno"));
        listaEventosFolha.add(new EventosFolha(null, "15", "Desconto Horas Atrasos e/ou Saídas"));
        listaEventosFolha.add(new EventosFolha(null, "16", "salário Simbólico para Cálculo FGTS"));
        listaEventosFolha.add(new EventosFolha(null, "17", "Pró-labore"));
        listaEventosFolha.add(new EventosFolha(null, "18", "Desconto dias de faltas - Feriado"));
        listaEventosFolha.add(new EventosFolha(null, "19", "Bolsa Auxílio"));
        listaEventosFolha.add(new EventosFolha(null, "23", "Suspensão Disciplinar"));
        listaEventosFolha.add(new EventosFolha(null, "25", "Horas repouso remunerado noturno"));
        listaEventosFolha.add(new EventosFolha(null, "26", "DSR Sobre Hora extra 50%"));
        listaEventosFolha.add(new EventosFolha(null, "27", "DSR Sobre Hora extra 75%"));
        listaEventosFolha.add(new EventosFolha(null, "28", "DSR Sobre Hora extra 100%"));
        listaEventosFolha.add(new EventosFolha(null, "44", "Desconto Adiantamento salário"));
        listaEventosFolha.add(new EventosFolha(null, "45", "Diferença salário Mês anterior"));
        listaEventosFolha.add(new EventosFolha(null, "46", "Adicional Insalubridade"));
        listaEventosFolha.add(new EventosFolha(null, "47", "Adicional Periculosidade"));
        listaEventosFolha.add(new EventosFolha(null, "48", "Diferença Férias"));
        listaEventosFolha.add(new EventosFolha(null, "49", "Diferença Dissídio"));
        listaEventosFolha.add(new EventosFolha(null, "51", "Comissões"));
        listaEventosFolha.add(new EventosFolha(null, "52", "Integração Comissões sem Repouso"));
        listaEventosFolha.add(new EventosFolha(null, "53", "Gratificações"));
        listaEventosFolha.add(new EventosFolha(null, "54", "Quebra de Caixa"));
        listaEventosFolha.add(new EventosFolha(null, "55", "Estimativa Gorjeta"));
        listaEventosFolha.add(new EventosFolha(null, "56", "Prêmio Frequência"));
        listaEventosFolha.add(new EventosFolha(null, "98", "Horas extras 50%"));
        listaEventosFolha.add(new EventosFolha(null, "99", "Horas extras 70%"));
        listaEventosFolha.add(new EventosFolha(null, "100", "Horas extras 100%"));
        listaEventosFolha.add(new EventosFolha(null, "101", "salário Maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "102", "Horas extras 50Sobre salário Maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "103", "Horas extras 70Sobre salário Maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "104", "Horas extras 100Sobre salário Maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "105", "DSR Diurno Sobre salário Maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "106", "DSR noturno Sobre salário Maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "107", "Adicional noturno Sobre salário Maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "116", "Integração Horas extras e Variáveis Repouso"));
        listaEventosFolha.add(new EventosFolha(null, "117", "Integração de Horas Noturnas"));
        listaEventosFolha.add(new EventosFolha(null, "130", "Ajuda de Custo"));
        listaEventosFolha.add(new EventosFolha(null, "131", "Desconto salário Maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "132", "Auxílio Natalidade"));
        listaEventosFolha.add(new EventosFolha(null, "133", "salário Família"));
        listaEventosFolha.add(new EventosFolha(null, "134", "salário Paternidade"));
        listaEventosFolha.add(new EventosFolha(null, "140", "30 dias de Férias Gozadas - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "141", "20 dias de Férias Gozadas - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "142", "15 dias de Férias Gozadas - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "143", "10 dias de Férias Gozadas - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "144", "dias de Férias Gozadas - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "145", "1/3 De Férias"));
        listaEventosFolha.add(new EventosFolha(null, "146", "Abono Pecuniário - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "147", "1/3 Abono Pecuniário - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "148", "média horas extras 50- Férias"));
        listaEventosFolha.add(new EventosFolha(null, "149", "média horas extras 100- Férias"));
        listaEventosFolha.add(new EventosFolha(null, "150", "média horas extras 70- Férias"));
        listaEventosFolha.add(new EventosFolha(null, "151", "Adicional Insalubridade - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "152", "Adicional Periculosidade - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "153", "Média Comissões - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "154", "média adicional noturno - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "155", "Desconto dias Redução para faltas - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "156", "Férias em Dobro - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "157", "1/3 Constitucional Férias em Dobro - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "158", "INSS Sobre Férias"));
        listaEventosFolha.add(new EventosFolha(null, "159", "IRRF Sobre Férias"));
        listaEventosFolha.add(new EventosFolha(null, "167", "Adiantamento 1° Parcela 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "168", "Adiantamento 13º salário Horas extras 50%"));
        listaEventosFolha.add(new EventosFolha(null, "169", "Adiantamento 13º salário Horas extras 70%"));
        listaEventosFolha.add(new EventosFolha(null, "170", "Adiantamento 13º salário Horas extras 100%"));
        listaEventosFolha.add(new EventosFolha(null, "171", "Adiantamento 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "172", "Adiantamento 13º salário - Desconto"));
        listaEventosFolha.add(new EventosFolha(null, "176", "DSR Diurno Sobre 1° Parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "177", "DSR noturno Sobre 1° Parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "178", "Insalubridade Sobre 1° Parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "179", "Periculosidade Sobre 1° Parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "182", "13º salário Final Horas extras 50%"));
        listaEventosFolha.add(new EventosFolha(null, "183", "13º salário Final Horas extras 70%"));
        listaEventosFolha.add(new EventosFolha(null, "184", "13º salário Final Horas extras 100%"));
        listaEventosFolha.add(new EventosFolha(null, "185", "DSR Diurno Sobre 2° Parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "186", "DSR noturno Sobre 2° Parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "187", "Insalubridade Sobre 2° Parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "188", "Periculosidade Sobre 2° Parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "189", "2° Parcela 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "190", "Desconto Adiantamento 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "194", "13º salário Final Horas extras e Adicional sem Repouso"));
        listaEventosFolha.add(new EventosFolha(null, "195", "13º salário Final Média Comissões"));
        listaEventosFolha.add(new EventosFolha(null, "200", "13º salário Final Comissão sem Repouso"));
        listaEventosFolha.add(new EventosFolha(null, "201", "Complemento média hora extra 50do 13°"));
        listaEventosFolha.add(new EventosFolha(null, "202", "Complemento média hora extra 70do 13°"));
        listaEventosFolha.add(new EventosFolha(null, "203", "Complemento média hora extra 100do 13°"));
        listaEventosFolha.add(new EventosFolha(null, "204", "Complemento Média Ref. DSR Diurno"));
        listaEventosFolha.add(new EventosFolha(null, "205", "Complemento Média Ref. DSR noturno"));
        listaEventosFolha.add(new EventosFolha(null, "206", "13º salário média adicional noturno"));
        listaEventosFolha.add(new EventosFolha(null, "229", "Empréstimo consignado"));
        listaEventosFolha.add(new EventosFolha(null, "230", "Desconto empréstimo"));
        listaEventosFolha.add(new EventosFolha(null, "231", "Vale alimentação"));
        listaEventosFolha.add(new EventosFolha(null, "232", "Vale farmácia"));
        listaEventosFolha.add(new EventosFolha(null, "233", "Vale refeição"));
        listaEventosFolha.add(new EventosFolha(null, "235", "Convênio assistência médica"));
        listaEventosFolha.add(new EventosFolha(null, "236", "Seguro de vida"));
        listaEventosFolha.add(new EventosFolha(null, "238", "Desconto seguro vida"));
        listaEventosFolha.add(new EventosFolha(null, "239", "Vale Transporte"));
        listaEventosFolha.add(new EventosFolha(null, "241", "Desconto vale transporte"));
        listaEventosFolha.add(new EventosFolha(null, "242", "Convênio Assistência Odontológica"));
        listaEventosFolha.add(new EventosFolha(null, "243", "Coparticipação Assistência Médica"));
        listaEventosFolha.add(new EventosFolha(null, "244", "Desconto INSS"));
        listaEventosFolha.add(new EventosFolha(null, "245", "INSS Sobre 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "246", "Desconto IRRF"));
        listaEventosFolha.add(new EventosFolha(null, "247", "IRRF Sobre 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "248", "Pensão alimentícia"));
        listaEventosFolha.add(new EventosFolha(null, "256", "Coparticipação assistência odontológica"));
        listaEventosFolha.add(new EventosFolha(null, "259", "Vale creche"));
        listaEventosFolha.add(new EventosFolha(null, "260", "Dia desconto contribuição sindical"));
        listaEventosFolha.add(new EventosFolha(null, "302", "dias Saldo salário"));
        listaEventosFolha.add(new EventosFolha(null, "303", "Dias aviso prévio Trabalhados"));
        listaEventosFolha.add(new EventosFolha(null, "304", "Dias aviso prévio Indenizados"));
        listaEventosFolha.add(new EventosFolha(null, "305", "Multa do FGTS"));
        listaEventosFolha.add(new EventosFolha(null, "306", "Férias proporcionais"));
        listaEventosFolha.add(new EventosFolha(null, "307", "Férias Vencidas"));
        listaEventosFolha.add(new EventosFolha(null, "308", "média horas extras Férias proporcionais"));
        listaEventosFolha.add(new EventosFolha(null, "309", "Insalubridade Férias proporcionais"));
        listaEventosFolha.add(new EventosFolha(null, "310", "Periculosidade Férias proporcionais"));
        listaEventosFolha.add(new EventosFolha(null, "311", "média adicional noturno Férias proporcionais"));
        listaEventosFolha.add(new EventosFolha(null, "312", "salário Família"));
        listaEventosFolha.add(new EventosFolha(null, "313", "INSS sem aviso prévio"));
        listaEventosFolha.add(new EventosFolha(null, "314", "IRRF Participação nos Lucros"));
        listaEventosFolha.add(new EventosFolha(null, "315", "Média Comissões Férias proporcionais"));
        listaEventosFolha.add(new EventosFolha(null, "316", "média horas extras Férias"));
        listaEventosFolha.add(new EventosFolha(null, "317", "Adiantamento 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "318", "Média Triênio Férias proporcionais"));
        listaEventosFolha.add(new EventosFolha(null, "319", "Média Quinquênio Férias proporcionais"));
        listaEventosFolha.add(new EventosFolha(null, "324", "1/3 Férias Constitucional"));
        listaEventosFolha.add(new EventosFolha(null, "325", "13º salário proporcional"));
        listaEventosFolha.add(new EventosFolha(null, "326", "Insalubridade 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "327", "Periculosidade 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "328", "média horas extras 13º salário proporcional"));
        listaEventosFolha.add(new EventosFolha(null, "329", "Adicional noturno 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "330", "Comissões 13º salário proporcional"));
        listaEventosFolha.add(new EventosFolha(null, "331", "Multa Art. 476-A §5º CLT"));
        listaEventosFolha.add(new EventosFolha(null, "332", "Média adicional noturno"));
        listaEventosFolha.add(new EventosFolha(null, "333", "Insalubridade"));
        listaEventosFolha.add(new EventosFolha(null, "335", "Insalubridade 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "336", "Periculosidade"));
        listaEventosFolha.add(new EventosFolha(null, "338", "Hora extra 50%"));
        listaEventosFolha.add(new EventosFolha(null, "339", "Hora extra 70%"));
        listaEventosFolha.add(new EventosFolha(null, "340", "Hora extra 100%"));
        listaEventosFolha.add(new EventosFolha(null, "342", "Desconto vale transporte"));
        listaEventosFolha.add(new EventosFolha(null, "343", "Desconto vale refeição"));
        listaEventosFolha.add(new EventosFolha(null, "347", "Faltas Calculadas nas Férias"));
        listaEventosFolha.add(new EventosFolha(null, "349", "Faltas"));
        listaEventosFolha.add(new EventosFolha(null, "350", "1/12 Avos 13º salário sem aviso prévio"));
        listaEventosFolha.add(new EventosFolha(null, "351", "1/12 Avos Férias sem aAviso prévio indenizado"));
        listaEventosFolha.add(new EventosFolha(null, "352", "1/12 Avos 13º salário com aviso Prévio"));
        listaEventosFolha.add(new EventosFolha(null, "353", "1/12 Avos Férias com aviso prévio indenizado"));
        listaEventosFolha.add(new EventosFolha(null, "402", "FGTS Normal Deposito"));
        listaEventosFolha.add(new EventosFolha(null, "403", "FGTS 13º salário Deposito"));
        listaEventosFolha.add(new EventosFolha(null, "404", "Dedução dependentes IRRF"));
        listaEventosFolha.add(new EventosFolha(null, "405", "Dedução dependentes IRRF sem Férias"));
        listaEventosFolha.add(new EventosFolha(null, "407", "Dedução dependentes IRRF sem 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "408", "Prévia IRRF"));
        listaEventosFolha.add(new EventosFolha(null, "409", "Participação nos lucros e resultados"));
        listaEventosFolha.add(new EventosFolha(null, "410", "abono salarial"));
        listaEventosFolha.add(new EventosFolha(null, "412", "Reembolso creche"));
        listaEventosFolha.add(new EventosFolha(null, "414", "Gratificação semestral"));
        listaEventosFolha.add(new EventosFolha(null, "416", "Viagens"));
        listaEventosFolha.add(new EventosFolha(null, "417", "1° Parcela P.L.R"));
        listaEventosFolha.add(new EventosFolha(null, "418", "2° Parcela P.L.R"));
        listaEventosFolha.add(new EventosFolha(null, "420", "1° Parcela abono salarial"));
        listaEventosFolha.add(new EventosFolha(null, "421", "2° Parcela abono salarial"));
        listaEventosFolha.add(new EventosFolha(null, "422", "Arredondamento anterior"));
        listaEventosFolha.add(new EventosFolha(null, "423", "Arredondamento atual"));
        listaEventosFolha.add(new EventosFolha(null, "424", "Desconto complementar Insuficiência Saldo"));
        listaEventosFolha.add(new EventosFolha(null, "425", "Complemento para Insuficiência de Saldo"));
        listaEventosFolha.add(new EventosFolha(null, "426", "Retenção INSS Empregador"));
        listaEventosFolha.add(new EventosFolha(null, "427", "pensão alimentícia sem Líquido Férias"));
        listaEventosFolha.add(new EventosFolha(null, "428", "Prévia IRRF sem Férias"));
        listaEventosFolha.add(new EventosFolha(null, "429", "Prévia IRRF sem 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "430", "Prévia pensão alimentícia"));
        listaEventosFolha.add(new EventosFolha(null, "431", "Prévia pensão alimentícia sem Férias"));
        listaEventosFolha.add(new EventosFolha(null, "432", "Prévia pensão alimentícia sem 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "433", "Desconto contribuição assistencial"));

        eventosFolhaRepository.saveAll(listaEventosFolha);
    }
}
