package br.com.codex.v1.utilitario;

import br.com.codex.v1.domain.repository.EventosFolhaRepository;
import br.com.codex.v1.domain.rh.EventosFolha;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
public class ImportaEventosFolha {

    @Autowired
    private EventosFolhaRepository eventosFolhaRepository;

    public void importaEventosFolha(){

        List<EventosFolha> listaEventosFolha = new ArrayList<>();

        listaEventosFolha.add(new EventosFolha(null, "1", "Normais Diurnas"));
        listaEventosFolha.add(new EventosFolha(null, "2", "Adiantamento Salário"));
        listaEventosFolha.add(new EventosFolha(null, "5", "Horas Repouso Remunerado Diruno"));
        listaEventosFolha.add(new EventosFolha(null, "6", "Desconto Dias de Faltas"));
        listaEventosFolha.add(new EventosFolha(null, "7", "Desconto Dias de Descanso Semanal Remunerado (DSR)"));
        listaEventosFolha.add(new EventosFolha(null, "8", "Horas de Atestado Médico"));
        listaEventosFolha.add(new EventosFolha(null, "9", "Dias de atestado médico"));
        listaEventosFolha.add(new EventosFolha(null, "12", "Horas Normais Noturnas"));
        listaEventosFolha.add(new EventosFolha(null, "13", "Redução Horário Noturno"));
        listaEventosFolha.add(new EventosFolha(null, "14", "% Adicional Noturno"));
        listaEventosFolha.add(new EventosFolha(null, "15", "Desconto Horas Atrasos e/ou Saídas"));
        listaEventosFolha.add(new EventosFolha(null, "16", "Salário Simbólico p/ Cálculo FGTS"));
        listaEventosFolha.add(new EventosFolha(null, "17", "Pró-labore"));
        listaEventosFolha.add(new EventosFolha(null, "18", "Desconto Dias de Faltas - Feriado"));
        listaEventosFolha.add(new EventosFolha(null, "19", "Bolsa Auxílio"));
        listaEventosFolha.add(new EventosFolha(null, "23", "Suspensão Disciplinar"));
        listaEventosFolha.add(new EventosFolha(null, "25", "Horas Repouso Remunerado Noturno"));
        listaEventosFolha.add(new EventosFolha(null, "26", "DSR Sobre Hora Extra 50%"));
        listaEventosFolha.add(new EventosFolha(null, "27", "DSR Sobre Hora Extra 75%"));
        listaEventosFolha.add(new EventosFolha(null, "28", "DSR Sobre Hora Extra 100%"));
        listaEventosFolha.add(new EventosFolha(null, "44", "Desconto Adiantamento Salário"));
        listaEventosFolha.add(new EventosFolha(null, "45", "Diferença Salário Mês Anterior"));
        listaEventosFolha.add(new EventosFolha(null, "46", "Adicional Insalubridade"));
        listaEventosFolha.add(new EventosFolha(null, "47", "Adicional Periculosidade"));
        listaEventosFolha.add(new EventosFolha(null, "48", "Diferença Férias"));
        listaEventosFolha.add(new EventosFolha(null, "49", "Diferença Dissídio"));
        listaEventosFolha.add(new EventosFolha(null, "51", "% Comissões"));
        listaEventosFolha.add(new EventosFolha(null, "52", "Integração Comissões s/ Repouso"));
        listaEventosFolha.add(new EventosFolha(null, "53", "Gratificações"));
        listaEventosFolha.add(new EventosFolha(null, "54", "% Quebra de Caixa"));
        listaEventosFolha.add(new EventosFolha(null, "55", "% Estimativa Gorjeta"));
        listaEventosFolha.add(new EventosFolha(null, "56", "% Prêmio Frequência"));
        listaEventosFolha.add(new EventosFolha(null, "98", "Horas Extras 50%"));
        listaEventosFolha.add(new EventosFolha(null, "99", "Horas Extras 70%"));
        listaEventosFolha.add(new EventosFolha(null, "100", "Horas Extras 100%"));
        listaEventosFolha.add(new EventosFolha(null, "101", "Salário Maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "102", "Horas Extras 50% Sobre Salário Maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "103", "Horas Extras 70% Sobre Salário Maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "104", "Horas Extras 100% Sobre Salário Maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "105", "DSR Diurno Sobre Salário Maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "106", "DSR Noturno Sobre Salário Maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "107", "Adicional Noturno Sobre Salário Maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "116", "Integração Horas Extras e Variáveis Repouso"));
        listaEventosFolha.add(new EventosFolha(null, "117", "Integração de Horas Noturnas"));
        listaEventosFolha.add(new EventosFolha(null, "130", "Ajuda de Custo"));
        listaEventosFolha.add(new EventosFolha(null, "131", "Desconto Salário Maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "132", "Auxílio Natalidade"));
        listaEventosFolha.add(new EventosFolha(null, "133", "Salário Família"));
        listaEventosFolha.add(new EventosFolha(null, "134", "Salário Paternidade"));
        listaEventosFolha.add(new EventosFolha(null, "140", "30 Dias de Férias Gozadas - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "141", "20 Dias de Férias Gozadas - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "142", "15 Dias de Férias Gozadas - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "143", "10 Dias de Férias Gozadas - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "144", "Dias de Férias Gozadas - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "145", "1/3 De Férias"));
        listaEventosFolha.add(new EventosFolha(null, "146", "Abono Pecuniário - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "147", "1/3 Abono Pecuniário - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "148", "Média Horas Extras 50% - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "149", "Média Horas Extras 100% - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "150", "Média Horas Extras 70% - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "151", "Adicional Insalubridade - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "152", "Adicional Periculosidade - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "153", "Média Comissões - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "154", "Média Adicional Noturno - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "155", "Desconto Dias Redução p/ Faltas - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "156", "Férias em Dobro - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "157", "1/3 Constitucional Férias em Dobro - Férias"));
        listaEventosFolha.add(new EventosFolha(null, "158", "% INSS Sobre Férias"));
        listaEventosFolha.add(new EventosFolha(null, "159", "% IRF Sobre Férias"));
        listaEventosFolha.add(new EventosFolha(null, "167", "Adiantamento 1° Parcela 13º Salário"));
        listaEventosFolha.add(new EventosFolha(null, "168", "Adiantamento 13º Salário Horas Extras 50%"));
        listaEventosFolha.add(new EventosFolha(null, "169", "Adiantamento 13º Salário Horas Extras 70%"));
        listaEventosFolha.add(new EventosFolha(null, "170", "Adiantamento 13º Salário Horas Extras 100%"));
        listaEventosFolha.add(new EventosFolha(null, "171", "Adiantamento 13º Salário"));
        listaEventosFolha.add(new EventosFolha(null, "172", "Adiantamento 13º Salário - Desconto"));
        listaEventosFolha.add(new EventosFolha(null, "176", "DSR Diurno Sobre 1° Parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "177", "DSR Noturno Sobre 1° Parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "178", "Insalubridade Sobre 1° Parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "179", "Periculosidade Sobre 1° Parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "182", "13º Salário Final Horas Extras 50%"));
        listaEventosFolha.add(new EventosFolha(null, "183", "13º Salário Final Horas Extras 70%"));
        listaEventosFolha.add(new EventosFolha(null, "184", "13º Salário Final Horas Extras 100%"));
        listaEventosFolha.add(new EventosFolha(null, "185", "DSR Diurno Sobre 2° Parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "186", "DSR Noturno Sobre 2° Parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "187", "Insalubridade Sobre 2° Parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "188", "Periculosidade Sobre 2° Parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "189", "2° Parcela 13º Salário"));
        listaEventosFolha.add(new EventosFolha(null, "190", "Desconto Adiantamento 13º Salário"));
        listaEventosFolha.add(new EventosFolha(null, "194", "13º Salário Final Horas Extras e Adicional s/ Repouso"));
        listaEventosFolha.add(new EventosFolha(null, "195", "13º Salário Final Média Comissões"));
        listaEventosFolha.add(new EventosFolha(null, "200", "13º Salário Final Comissão s/ Repouso"));
        listaEventosFolha.add(new EventosFolha(null, "201", "Complemento Média Hora Extra 50% do 13°"));
        listaEventosFolha.add(new EventosFolha(null, "202", "Complemento Média Hora Extra 70% do 13°"));
        listaEventosFolha.add(new EventosFolha(null, "203", "Complemento Média Hora Extra 100% do 13°"));
        listaEventosFolha.add(new EventosFolha(null, "204", "Complemento Média Ref. DSR Diurno"));
        listaEventosFolha.add(new EventosFolha(null, "205", "Complemento Média Ref. DSR Noturno"));
        listaEventosFolha.add(new EventosFolha(null, "206", "13º Salário Média Adicional Noturno"));
        listaEventosFolha.add(new EventosFolha(null, "229", "Empréstimo Consignado"));
        listaEventosFolha.add(new EventosFolha(null, "230", "Desconto Empréstimo - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "231", "Vale Alimentação"));
        listaEventosFolha.add(new EventosFolha(null, "232", "Vale Farmácia"));
        listaEventosFolha.add(new EventosFolha(null, "233", "Vale Refeição"));
        listaEventosFolha.add(new EventosFolha(null, "235", "Convênio Assistência Médica"));
        listaEventosFolha.add(new EventosFolha(null, "236", "Seguro de Vida"));
        listaEventosFolha.add(new EventosFolha(null, "238", "Desconto Seguro Vida"));
        listaEventosFolha.add(new EventosFolha(null, "239", "Vale Transporte"));
        listaEventosFolha.add(new EventosFolha(null, "241", "6% Desconto Vale Transporte"));
        listaEventosFolha.add(new EventosFolha(null, "242", "Convênio Assistência Odontológica"));
        listaEventosFolha.add(new EventosFolha(null, "243", "Coparticipação Assistência Médica"));
        listaEventosFolha.add(new EventosFolha(null, "244", "% Desconto INSS"));
        listaEventosFolha.add(new EventosFolha(null, "245", "% INSS Sobre 13º Salário"));
        listaEventosFolha.add(new EventosFolha(null, "246", "% Desconto IRF"));
        listaEventosFolha.add(new EventosFolha(null, "247", "% IRF Sobre 13º Salário"));
        listaEventosFolha.add(new EventosFolha(null, "248", "% Pensão Alimentícia"));
        listaEventosFolha.add(new EventosFolha(null, "256", "Coparticipação Assistência Odontológica"));
        listaEventosFolha.add(new EventosFolha(null, "259", "Vale Creche"));
        listaEventosFolha.add(new EventosFolha(null, "260", "Dia Desconto Contribuição Sindical"));
        listaEventosFolha.add(new EventosFolha(null, "302", "Dias Saldo Salário - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "303", "Dias Aviso Prévio Trabalhados - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "304", "Dias Aviso Prévio Indenizados - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "305", "Multa do FGTS - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "306", "Férias Proporcionais - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "307", "Férias Vencidas - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "308", "Média Horas Extras Férias Proporcionais - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "309", "Insalubridade Férias Proporcionais - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "310", "Periculosidade Férias Proporcionais - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "311", "Média Adicional Noturno Férias Proporcionais - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "312", "Salário Família - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "313", "% INSS s/ Aviso Prévio - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "314", "% IRF Participação nos Lucros - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "315", "Média Comissões Férias Proporcionais - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "316", "Média Horas Extras Férias - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "317", "Adiantamento 13º Salário - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "318", "Média Triênio Férias Proporcionais - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "319", "Média Quinquênio Férias Proporcionais - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "324", "1/3 Férias Constitucional - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "325", "13º Salário Proporcional - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "326", "Insalubridade 13º Salário - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "327", "Periculosidade 13º Salário - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "328", "Média Horas Extras 13º Salário Proporcional - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "329", "Adicional Noturno 13º Salário - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "330", "Comissões 13º Salário Proporcional - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "331", "Multa Art. 476-A §5º CLT"));
        listaEventosFolha.add(new EventosFolha(null, "332", "Média Adicional Noturno - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "333", "Insalubridade - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "335", "Insalubridade 13º Salário - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "336", "Periculosidade - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "338", "Hora Extra 50% - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "339", "Hora Extra 70% - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "340", "Hora Extra 100% - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "342", "Desconto Vale Transporte - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "343", "Desconto Vale Refeição - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "347", "Faltas Calculadas nas Férias - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "349", "Faltas - Rescisão"));
        listaEventosFolha.add(new EventosFolha(null, "350", "1/12 Avos 13º Salário s/ Aviso Prévio"));
        listaEventosFolha.add(new EventosFolha(null, "351", "1/12 Avos Férias s/ Aviso Prévio. Inden."));
        listaEventosFolha.add(new EventosFolha(null, "352", "1/12 Avos 13º Salário C/ Aviso Prévio"));
        listaEventosFolha.add(new EventosFolha(null, "353", "1/12 Avos Férias C/ Aviso Prévio. Inden."));
        listaEventosFolha.add(new EventosFolha(null, "402", "FGTS Normal Deposito"));
        listaEventosFolha.add(new EventosFolha(null, "403", "FGTS 13º Salário Deposito"));
        listaEventosFolha.add(new EventosFolha(null, "404", "Dedução Dependentes IRF"));
        listaEventosFolha.add(new EventosFolha(null, "405", "Dedução Dependentes IRF s/ Férias"));
        listaEventosFolha.add(new EventosFolha(null, "407", "Dedução Dependentes IRF s/ 13º Salário"));
        listaEventosFolha.add(new EventosFolha(null, "408", "Prévia IRF"));
        listaEventosFolha.add(new EventosFolha(null, "409", "Participação nos Lucros e Resultados"));
        listaEventosFolha.add(new EventosFolha(null, "410", "Abono Salarial"));
        listaEventosFolha.add(new EventosFolha(null, "412", "Reembolso creche"));
        listaEventosFolha.add(new EventosFolha(null, "414", "Gratificação Semestral"));
        listaEventosFolha.add(new EventosFolha(null, "416", "Viagens"));
        listaEventosFolha.add(new EventosFolha(null, "417", "1° Parcela P.L.R"));
        listaEventosFolha.add(new EventosFolha(null, "418", "2° Parcela P.L.R"));
        listaEventosFolha.add(new EventosFolha(null, "420", "1° Parcela Abono Salarial"));
        listaEventosFolha.add(new EventosFolha(null, "421", "2° Parcela Abono Salarial"));
        listaEventosFolha.add(new EventosFolha(null, "422", "Arredondamento Anterior"));
        listaEventosFolha.add(new EventosFolha(null, "423", "Arredondamento Atual"));
        listaEventosFolha.add(new EventosFolha(null, "424", "Desconto Complementar Insuficiência Saldo"));
        listaEventosFolha.add(new EventosFolha(null, "425", "Complemento p/ Insuficiência de Saldo"));
        listaEventosFolha.add(new EventosFolha(null, "426", "Retenção INSS Empregador"));
        listaEventosFolha.add(new EventosFolha(null, "427", "Pensão Alimentícia s/ Líquido Férias"));
        listaEventosFolha.add(new EventosFolha(null, "428", "Prévia IRF s/ Férias"));
        listaEventosFolha.add(new EventosFolha(null, "429", "Prévia IRF s/ 13º Salário"));
        listaEventosFolha.add(new EventosFolha(null, "430", "Prévia Pensão Alimentícia"));
        listaEventosFolha.add(new EventosFolha(null, "431", "Prévia Pensão Alimentícia s/ Férias"));
        listaEventosFolha.add(new EventosFolha(null, "432", "Prévia Pensão Alimentícia s/ 13º Salário"));
        listaEventosFolha.add(new EventosFolha(null, "433", "Desconto Contribuição Assistencial"));

        eventosFolhaRepository.saveAll(listaEventosFolha);
    }
}
