package br.com.codex.v1.utilitario;

import br.com.codex.v1.domain.repository.EventosFolhaRepository;
import br.com.codex.v1.domain.rh.EventosFolha;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
public class ImportaEventosFolha {

    @Autowired
    private EventosFolhaRepository eventosFolhaRepository;

    public void importaEventosFolha(){

        List<EventosFolha> listaEventosFolha = new ArrayList<>();

        listaEventosFolha.add(new EventosFolha(null, "1", "Normais diurnas"));
        listaEventosFolha.add(new EventosFolha(null, "2", "Adiantamento salário"));
        listaEventosFolha.add(new EventosFolha(null, "5", "Horas repouso remunerado diurno"));
        listaEventosFolha.add(new EventosFolha(null, "6", "Desconto dias de faltas"));
        listaEventosFolha.add(new EventosFolha(null, "7", "Desconto dias de descanso semanal remunerado (DSR)"));
        listaEventosFolha.add(new EventosFolha(null, "8", "Horas de atestado médico"));
        listaEventosFolha.add(new EventosFolha(null, "9", "Dias de atestado médico"));
        listaEventosFolha.add(new EventosFolha(null, "12", "Horas normais noturnas"));
        listaEventosFolha.add(new EventosFolha(null, "13", "Redução horário noturno"));
        listaEventosFolha.add(new EventosFolha(null, "14", "Adicional noturno"));
        listaEventosFolha.add(new EventosFolha(null, "15", "Desconto horas atrasos e/ou Saídas"));
        listaEventosFolha.add(new EventosFolha(null, "16", "salário simbólico para cCálculo FGTS"));
        listaEventosFolha.add(new EventosFolha(null, "17", "Pró-labore"));
        listaEventosFolha.add(new EventosFolha(null, "18", "Desconto por faltas em feriado"));
        listaEventosFolha.add(new EventosFolha(null, "19", "Bolsa auxílio"));
        listaEventosFolha.add(new EventosFolha(null, "23", "Suspensão disciplinar"));
        listaEventosFolha.add(new EventosFolha(null, "25", "Horas repouso remunerado noturno"));
        listaEventosFolha.add(new EventosFolha(null, "26", "DSR sobre hora extra 50%"));
        listaEventosFolha.add(new EventosFolha(null, "27", "DSR sobre hora extra 75%"));
        listaEventosFolha.add(new EventosFolha(null, "28", "DSR sobre hora extra 100%"));
        listaEventosFolha.add(new EventosFolha(null, "44", "Desconto adiantamento salário"));
        listaEventosFolha.add(new EventosFolha(null, "45", "Diferença salário Mês anterior"));// ver este caso aqui
        listaEventosFolha.add(new EventosFolha(null, "46", "Adicional insalubridade"));
        listaEventosFolha.add(new EventosFolha(null, "47", "Adicional periculosidade"));
        listaEventosFolha.add(new EventosFolha(null, "48", "Diferença férias")); // ver este caso aqui
        listaEventosFolha.add(new EventosFolha(null, "49", "Diferença dissídio"));// ver este caso aqui
        listaEventosFolha.add(new EventosFolha(null, "51", "Comissões"));
        listaEventosFolha.add(new EventosFolha(null, "52", "Integração comissões sem repouso"));// ver este caso aqui
        listaEventosFolha.add(new EventosFolha(null, "53", "Gratificações"));
        listaEventosFolha.add(new EventosFolha(null, "54", "Quebra de caixa"));
        listaEventosFolha.add(new EventosFolha(null, "55", "Estimativa gorjeta"));
        listaEventosFolha.add(new EventosFolha(null, "56", "Prêmio frequência"));
        listaEventosFolha.add(new EventosFolha(null, "98", "Horas extras 50%"));
        listaEventosFolha.add(new EventosFolha(null, "99", "Horas extras 70%"));
        listaEventosFolha.add(new EventosFolha(null, "100", "Horas extras 100%"));
        listaEventosFolha.add(new EventosFolha(null, "101", "salário maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "102", "Horas extras 50% sobre salário maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "103", "Horas extras 70% sobre salário maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "104", "Horas extras 100% sobre salário maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "105", "DSR Diurno sobre salário maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "106", "DSR noturno sobre salário maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "107", "Adicional noturno sobre salário maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "116", "Integração horas extras e variáveis repouso"));
        listaEventosFolha.add(new EventosFolha(null, "117", "Integração de horas noturnas"));
        listaEventosFolha.add(new EventosFolha(null, "130", "Ajuda de custo"));
        listaEventosFolha.add(new EventosFolha(null, "131", "Desconto salário maternidade"));
        listaEventosFolha.add(new EventosFolha(null, "132", "Auxílio natalidade"));
        listaEventosFolha.add(new EventosFolha(null, "133", "salário família"));
        listaEventosFolha.add(new EventosFolha(null, "134", "salário paternidade"));
        listaEventosFolha.add(new EventosFolha(null, "140", "30 dias de férias gozadas"));
        listaEventosFolha.add(new EventosFolha(null, "141", "20 dias de férias gozadas"));
        listaEventosFolha.add(new EventosFolha(null, "142", "15 dias de férias gozadas"));
        listaEventosFolha.add(new EventosFolha(null, "143", "10 dias de férias gozadas"));
        listaEventosFolha.add(new EventosFolha(null, "144", "Dias de férias gozadas"));
        listaEventosFolha.add(new EventosFolha(null, "145", "1/3 De férias"));
        listaEventosFolha.add(new EventosFolha(null, "146", "Abono pecuniário"));
        listaEventosFolha.add(new EventosFolha(null, "147", "1/3 Abono pecuniário"));
        listaEventosFolha.add(new EventosFolha(null, "148", "Média horas extras 50"));
        listaEventosFolha.add(new EventosFolha(null, "149", "Média horas extras 100"));
        listaEventosFolha.add(new EventosFolha(null, "150", "Média horas extras 70"));
        listaEventosFolha.add(new EventosFolha(null, "153", "Média comissões"));
        listaEventosFolha.add(new EventosFolha(null, "154", "Média adicional noturno"));
        listaEventosFolha.add(new EventosFolha(null, "155", "Desconto dias redução para faltas"));
        listaEventosFolha.add(new EventosFolha(null, "156", "Férias em dobro"));
        listaEventosFolha.add(new EventosFolha(null, "157", "1/3 Constitucional férias em dobro"));
        listaEventosFolha.add(new EventosFolha(null, "158", "INSS sobre férias"));
        listaEventosFolha.add(new EventosFolha(null, "159", "IRRF sobre férias"));
        listaEventosFolha.add(new EventosFolha(null, "167", "Adiantamento 1° parcela 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "168", "Adiantamento 13º salário horas extras 50%"));
        listaEventosFolha.add(new EventosFolha(null, "169", "Adiantamento 13º salário horas extras 70%"));
        listaEventosFolha.add(new EventosFolha(null, "170", "Adiantamento 13º salário horas extras 100%"));
        listaEventosFolha.add(new EventosFolha(null, "171", "Adiantamento 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "176", "DSR diurno sobre 1° parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "177", "DSR noturno sobre 1° parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "178", "Insalubridade sobre 1° parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "179", "Periculosidade sobre 1° parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "182", "2° parcela 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "183", "13º salário Final horas extras 50%"));
        listaEventosFolha.add(new EventosFolha(null, "184", "13º salário Final horas extras 70%"));
        listaEventosFolha.add(new EventosFolha(null, "185", "13º salário Final horas extras 100%"));
        listaEventosFolha.add(new EventosFolha(null, "186", "DSR diurno sobre 2° parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "187", "DSR noturno sobre 2° parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "188", "Insalubridade sobre 2° parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "189", "Periculosidade sobre 2° parcela 13°"));
        listaEventosFolha.add(new EventosFolha(null, "190", "Desconto adiantamento 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "194", "13º salário final horas extras e adicional sem repouso"));
        listaEventosFolha.add(new EventosFolha(null, "195", "13º salário final média Comissões"));
        listaEventosFolha.add(new EventosFolha(null, "200", "13º salário final Comissão sem Repouso"));
        listaEventosFolha.add(new EventosFolha(null, "201", "Complemento média hora extra 50% do 13°"));
        listaEventosFolha.add(new EventosFolha(null, "202", "Complemento média hora extra 70% do 13°"));
        listaEventosFolha.add(new EventosFolha(null, "203", "Complemento média hora extra 100% do 13°"));
        listaEventosFolha.add(new EventosFolha(null, "204", "Complemento mMédia referente ao DSR Diurno"));
        listaEventosFolha.add(new EventosFolha(null, "205", "Complemento mMédia referente ao DSR noturno"));
        listaEventosFolha.add(new EventosFolha(null, "206", "13º salário média adicional noturno"));
        listaEventosFolha.add(new EventosFolha(null, "229", "Empréstimo consignado"));
        listaEventosFolha.add(new EventosFolha(null, "230", "Desconto empréstimo"));
        listaEventosFolha.add(new EventosFolha(null, "231", "Vale alimentação"));
        listaEventosFolha.add(new EventosFolha(null, "232", "Vale farmácia"));
        listaEventosFolha.add(new EventosFolha(null, "233", "Vale refeição"));
        listaEventosFolha.add(new EventosFolha(null, "235", "Convênio assistência médica"));
        listaEventosFolha.add(new EventosFolha(null, "236", "Seguro de vida"));
        listaEventosFolha.add(new EventosFolha(null, "238", "Desconto seguro vida"));
        listaEventosFolha.add(new EventosFolha(null, "239", "Vale transporte"));
        listaEventosFolha.add(new EventosFolha(null, "241", "Desconto vale transporte"));
        listaEventosFolha.add(new EventosFolha(null, "242", "Convênio assistência odontológica"));
        listaEventosFolha.add(new EventosFolha(null, "243", "Coparticipação assistência médica"));
        listaEventosFolha.add(new EventosFolha(null, "244", "Desconto INSS"));
        listaEventosFolha.add(new EventosFolha(null, "245", "INSS sobre 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "246", "Desconto IRRF"));
        listaEventosFolha.add(new EventosFolha(null, "247", "IRRF sobre 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "248", "Pensão alimentícia"));
        listaEventosFolha.add(new EventosFolha(null, "256", "Coparticipação assistência odontológica"));
        listaEventosFolha.add(new EventosFolha(null, "259", "Vale creche"));
        listaEventosFolha.add(new EventosFolha(null, "260", "Dia desconto contribuição sindical"));
        listaEventosFolha.add(new EventosFolha(null, "302", "Dias saldo salário"));
        listaEventosFolha.add(new EventosFolha(null, "303", "Dias aviso prévio trabalhados"));
        listaEventosFolha.add(new EventosFolha(null, "304", "Dias aviso prévio indenizados"));
        listaEventosFolha.add(new EventosFolha(null, "305", "Multa do FGTS"));
        listaEventosFolha.add(new EventosFolha(null, "306", "Férias proporcionais"));
        listaEventosFolha.add(new EventosFolha(null, "307", "Férias Vencidas"));
        listaEventosFolha.add(new EventosFolha(null, "308", "Média horas extras férias proporcionais"));
        listaEventosFolha.add(new EventosFolha(null, "309", "Insalubridade férias proporcionais"));
        listaEventosFolha.add(new EventosFolha(null, "310", "Periculosidade férias proporcionais"));
        listaEventosFolha.add(new EventosFolha(null, "311", "Média adicional noturno férias proporcionais"));
        listaEventosFolha.add(new EventosFolha(null, "313", "INSS sem aviso prévio"));
        listaEventosFolha.add(new EventosFolha(null, "314", "IRRF participação nos lucros"));
        listaEventosFolha.add(new EventosFolha(null, "315", "Média comissões férias proporcionais"));
        listaEventosFolha.add(new EventosFolha(null, "316", "Média horas extras férias"));
        listaEventosFolha.add(new EventosFolha(null, "318", "Média triênio férias proporcionais"));
        listaEventosFolha.add(new EventosFolha(null, "319", "Média quinquênio férias proporcionais"));
        listaEventosFolha.add(new EventosFolha(null, "324", "1/3 férias Constitucional"));
        listaEventosFolha.add(new EventosFolha(null, "325", "13º salário proporcional"));
        listaEventosFolha.add(new EventosFolha(null, "326", "Insalubridade 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "327", "Periculosidade 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "328", "Média horas extras 13º salário proporcional"));
        listaEventosFolha.add(new EventosFolha(null, "329", "Adicional noturno 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "330", "Comissões 13º salário proporcional"));
        listaEventosFolha.add(new EventosFolha(null, "331", "Multa Art. 476-A §5º CLT"));
        listaEventosFolha.add(new EventosFolha(null, "332", "Média adicional noturno"));
        listaEventosFolha.add(new EventosFolha(null, "347", "Faltas calculadas nas férias"));
        listaEventosFolha.add(new EventosFolha(null, "349", "Faltas"));
        listaEventosFolha.add(new EventosFolha(null, "350", "1/12 Avos 13º salário sem aviso prévio"));
        listaEventosFolha.add(new EventosFolha(null, "351", "1/12 Avos férias sem aviso prévio indenizado"));
        listaEventosFolha.add(new EventosFolha(null, "352", "1/12 Avos 13º salário com aviso Prévio"));
        listaEventosFolha.add(new EventosFolha(null, "353", "1/12 Avos férias com aviso prévio indenizado"));
        listaEventosFolha.add(new EventosFolha(null, "402", "FGTS normal deposito"));
        listaEventosFolha.add(new EventosFolha(null, "403", "FGTS 13º salário deposito"));
        listaEventosFolha.add(new EventosFolha(null, "404", "Dedução dependentes IRRF"));
        listaEventosFolha.add(new EventosFolha(null, "405", "Dedução dependentes IRRF sem férias"));
        listaEventosFolha.add(new EventosFolha(null, "407", "Dedução dependentes IRRF sem 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "408", "Prévia IRRF"));
        listaEventosFolha.add(new EventosFolha(null, "409", "Participação nos lucros e resultados"));
        listaEventosFolha.add(new EventosFolha(null, "410", "Abono salarial"));
        listaEventosFolha.add(new EventosFolha(null, "412", "Reembolso creche"));
        listaEventosFolha.add(new EventosFolha(null, "414", "Gratificação semestral"));
        listaEventosFolha.add(new EventosFolha(null, "416", "Viagens"));
        listaEventosFolha.add(new EventosFolha(null, "417", "1° Parcela P.L.R"));
        listaEventosFolha.add(new EventosFolha(null, "418", "2° Parcela P.L.R"));
        listaEventosFolha.add(new EventosFolha(null, "420", "1° Parcela abono salarial"));
        listaEventosFolha.add(new EventosFolha(null, "421", "2° Parcela abono salarial"));
        listaEventosFolha.add(new EventosFolha(null, "422", "Arredondamento anterior"));
        listaEventosFolha.add(new EventosFolha(null, "423", "Arredondamento atual"));
        listaEventosFolha.add(new EventosFolha(null, "424", "Desconto complementar insuficiência saldo"));
        listaEventosFolha.add(new EventosFolha(null, "425", "Complemento para insuficiência de saldo"));
        listaEventosFolha.add(new EventosFolha(null, "426", "Retenção INSS empregador"));
        listaEventosFolha.add(new EventosFolha(null, "427", "pensão alimentícia sem líquido férias"));
        listaEventosFolha.add(new EventosFolha(null, "428", "Prévia IRRF sem férias"));
        listaEventosFolha.add(new EventosFolha(null, "429", "Prévia IRRF sem 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "430", "Prévia pensão alimentícia"));
        listaEventosFolha.add(new EventosFolha(null, "431", "Prévia pensão alimentícia sem férias"));
        listaEventosFolha.add(new EventosFolha(null, "432", "Prévia pensão alimentícia sem 13º salário"));
        listaEventosFolha.add(new EventosFolha(null, "433", "Desconto contribuição assistencial"));

        eventosFolhaRepository.saveAll(listaEventosFolha);
    }
}
